### ISSUE TITLE
Android certificate issue.

### ISSUE THREAD

**Issue by IzzySoft** [textbrowser/glitch#12]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by textbrowser** [comment]
Glitch isn't deployed to stores.

https://developer.android.com/studio/publish/app-signing

That is much mundane work. I am not going to start managing signing data. Nope.

**Comment by textbrowser** [comment]
I don't sign any APK. I just make-it-a-build and make-it-a-purge.

**Comment by IzzySoft** [comment]
Then I'll have to remove your app [from my repo](https://apt.izzysoft.de/packages/org.purple.glitch) unfortunately. Do you prefer that? No offense taken, just asking how to continue from here.

**Comment by textbrowser** [comment]
Glitch does not include sensitive information inside of it or outside of it. It possesses zero cryptographic purposes. The only official means of upgrading it is through GitHub. I cannot be responsible for other sites because I don't own those sites.

I provide APKs because they're easy to generate. There is also much thoughtful love written into the Android versions as Qt does not _perfectly_ function in Android as it does in other systems. And of course, the beauty of everyware-ness.

**Comment by IzzySoft** [comment]
OK, removed the app then, thanks. Be welcome to give me a ping should you want it re-listed one day.
